openapi: "3.0.1"
info:
  title: "Simple Measurement Report Protocol"
  description: "Report API for Measurement Reports"
  version: "1.0.0"

paths:
  /sMRep:
    post:
      summary: "Simple Measurment Report"
      operationId: "sMRep"
      description: ""
      requestBody:
        description: "Measuement Report"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SMRep'
        required: true
      responses:
        200:
          description: "Successful"
          content: {}
        400:
          description: "Bad Request"
          content: {}
        403:
          description: "Forbidden"
          content: {}
components:
  schemas:
    SMRep:
      type: "object"
      properties:
        reportingNode:
          type: "string"
        reportTs:
          type: integer
          format: int64
          description: "Timestamp. Time when Report is generated. Epoch milliseconds"
        msisdn:
          type: "string"
          description : "MSISDN in E164 international format. Included if available"
        imsi:
          type: "string"
          description : "IMSI in E212 format. Included if available"          
        imei:
          type: "string"
          description : "IMEI. Included if available. Note : Only one of imei and imeisv is included"          
        imeisv:
          type: "string"
          description : "IMEISV. Included if available. Note : Only one of imei and imeisv is included"          
        report:
          oneOf:
            - $ref: '#/components/schemas/SMRepLteRrcMRep'
            - $ref: '#/components/schemas/SMRepLteTARep'
              
    SMRepLteRrcMRep:
      type: "object"
      description : "LTE RRC Measuement Report"
      properties: 
        smrObjectType :
          type : string
          description : "Object Type identifier. Always SMRepLteRrcMRep"
          enum: [SMRepLteRrcMRep]
        servingPLMN:
          type : string
          description : "Serving PLMN, i.e. MCC + MNC"
        servingEnbId:
          type: "integer"
          format: int32
          description: "Serving eNodeB ID"
        servingCI:
          type: "integer"
          format: int16
          description: "Serving Cell ID"
        mmeUeS1apId:
          type: integer
          format: int64
          description: "MME UE ID" 
        enbUeS1apId:
          type: integer
          format: int64
          description: "eNodeB UE ID" 
        measurements:
          type: "array"
          description: "Array of measured values"
          items:
            $ref: '#/components/schemas/SMRepLteRrcMRepMeas'

    SMRepLteTARep:
      type: "object"
      description: "Simple TA Measurement Report"
      properties: 
        smrObjectType :
          type : string
          description : "Object Type identifier. Always SMRepLteTARep"
          enum: [SMRepLteTARep]
        servingPLMN:
          type : string
          description : "Serving PLMN, i.e. MCC + MNC"
        servingEnbId:
          type: "integer"
          format: int32
          description: "Serving eNodeB ID"
        servingCI:
          type: "integer"
          format: int16
          description: "Serving Cell ID"
        measTs:
          type: integer
          format: int64
          description: "Timestamp. Time for measurement value. Epoch milliseconds"
        ta1 :
          type : integer
          format: int32
          description : "TA1 value"
        ta2 :
          type : integer
          format: int32
          description : "TA2 value"
          
    SMRepLteRrcMRepMeas:
      type: object
      description: "LTE RRC Measurement Report Values"
      properties:
        smrObjectType :
          type : string
          description : "Object Type identifier. Always SMRepLteRrcMRepMeas"
          enum: [SMRepLteRrcMRepMeas]
        measTs :
          type : integer
          format : int64
          description : "Timestamp. Measurement timestamp. Epoch milliseconds"
        repEventType :
          type: string
          enum: [A1, A2, A3, A4, A5, A6, Periodic]
          description: "Event type"
        measEarfcn :
          type: integer
          format: int16
          description: "Measured Cell Earfcn"
        measPci:
          type: integer
          format: int16
          description: "Measured Cell PCI"
        rsrp:
          type: integer
          format: int16
          description: "Measured Cell RSRP"
        rsrq:
          type: integer
          format: int16
          description: "Measured Cell RSRQ"
        measCellGI :
          $ref: '#/components/schemas/LteCellGI'
          description: "Measured Cell ID. Optional. Included if available"
        measCellName :
          type : string
          description : "Measured Cell Name. Optional. Included if available"
        measCellInfo :
          type : string
          description : "Measured Cell Information. Optional. Included if available"

    LteCellGI:
      type: object
      description : "LTE Cell Global Identity"
      properties:
        mcc:
          type: string
        mnc:
          type: string
        enodebid:
          type: integer
          format: int32
        ci:
          type: integer
          format: int16
    UmtsCellGI:
      type: object
      description: "UMTS Cell Global Identity"
      properties:
        mcc:
          type: string
        mnc:
          type: string
        rncid:
          type: integer
          format: int16
        ci:
          type: integer
          format: int16
    GsmCellId:
      type: object
      description: "GSM Cell Global Identity"
      properties:
        mcc:
          type: string
        mnc:
          type: string
        lac:
          type: integer
          format: int16
        cid:
          type: integer
          format: int16
